# Generated by Django 4.2.20 on 2025-04-07 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_candidate_candidateproject_candidateskill_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bioitem",
            name="candidate",
            field=models.OneToOneField(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bio",
                to="main.candidate",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="candidateproject",
            name="candidate",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="candidate_projects",
                to="main.candidate",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="candidateskill",
            name="candidate",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="candidate_skills",
                to="main.candidate",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="contact",
            name="candidate",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contacts",
                to="main.candidate",
            ),
            preserve_default=False,
        ),
    ]
