# Generated by Django 4.2.20 on 2025-04-07 19:21

from django.db import migrations


def create_users(apps, schema_editor):
    User = apps.get_model("auth", "User")

    if not User.objects.filter(username="admin").exists():
        User.objects.create_superuser(
            username="admin", email="admin@admin.com", password="12345qwe"
        )

    if not User.objects.filter(username="user").exists():
        user = User.objects.create_user(
            username="user", email="user@user.com", password="12345qwe"
        )
        user.is_staff = False
        user.save()


class Migration(migrations.Migration):
    dependencies = [
        (
            "main",
            "0006_alter_bioitem_candidate_and_more",
        ),  # Replace with your real migration name (or keep as "000X_initial")
    ]

    operations = [
        migrations.RunPython(create_users),
    ]
