# Generated by Django 4.2.20 on 2025-04-08 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0007_auto_20250407_1921"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="project_name",
            field=models.CharField(max_length=255),
        ),
    ]
